modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "breedtimer"
version = "${version}"
displayName = "BreedTimer"
description = '''Shows floating timers above breedable animals indicating when they can breed again.'''
logoFile = "assets/breedtimer/icon.png"
authors = "Dennis_thegamer"

[[mixins]]
config = "breedtimer.mixins.json"

[[dependencies.breedtimer]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,26.3)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.breedtimer]]
modId = "neoforge"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.breedtimer]]
modId = "yet_another_config_lib_v3"
type = "optional"
versionRange = "[3.9.4,)"
ordering = "NONE"
side = "CLIENT"
