modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

issueTrackerURL = "https://github.com/DennisTheGamer/BreedTimer/issues"
[[mods]]
modId = "breedtimer"
version = "${version}"
displayName = "BreedTimer"
displayURL = "https://modrinth.com/mod/breedtimer"
description = '''Shows floating timers above breedable animals indicating when they can breed again.'''
logoFile = "assets/breedtimer/icon.png"
authors = "Dennis_thegamer"

[[mixins]]
config = "breedtimer.mixins.json"

[[dependencies.breedtimer]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.6,1.21.9)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.breedtimer]]
modId = "neoforge"
type = "required"
versionRange = "[21.6,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.breedtimer]]
modId = "yet_another_config_lib_v3"
type = "optional"
versionRange = "[3.8.2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.breedtimer]]
modId = "hudlib"
type = "required"
versionRange = "[1.0,)"
ordering = "NONE"
side = "CLIENT"
